name: maadm-spd

channels:
  - pytorch
  - conda-forge

dependencies:
  - python==3.10
  - conda-forge::pandas==2.0.0
  - conda-forge::numpy==1.26.0
  - conda-forge::scikit-learn==1.3.2
  - conda-forge::seaborn==0.13.0
  - conda-forge::python-dotenv==1.0.0
  - conda-forge::jupyterlab==4.0.8
  - conda-forge::xgboost==2.0.3
  - conda-forge::optuna==3.5.0
  - pip:
    - secml==0.15.6
